name: generate-builds
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    - name: Install dependencies
      run: |
        apk update
        apk add gcc g++ git make cmake samurai tar freeglut-dev glew-dev mesa-gl mesa-dev sdl2-dev libpng-dev libzip-dev nlohmann-json spdlog-dev sdl2_net-dev boost-dev lsb-release-minimal imagemagick python3
    - name: Install latest tinyxml2
      run: |
        wget https://github.com/leethomason/tinyxml2/archive/refs/tags/10.0.0.tar.gz
        tar -xzf 10.0.0.tar.gz
        cd tinyxml2-10.0.0
        mkdir build
        cd build
        cmake ..
        make && make install
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build SoH
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_REMOTE_CONTROL=1
        #cmake --build build-cmake --config Release --target GenerateSohOtr
        cmake --build build-cmake --config Release -j3
        (cd build-cmake && cpack -G External)

        mv README.md readme.txt
        mv build-cmake/*.appimage soh.appimage
      env:
        CC: gcc
        CXX: g++
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: soh-linux
        path: |
          soh.appimage
          readme.txt
